name: photo-hash
version: 0.3.0
summary: AsciiArt app
description: Convert images to text and images asciiart

confinement: strict
base: core18
grade: stable

slots:
  dbus-photo-hash: # adjust accordingly to your app name
    interface: dbus
    bus: session
    name: org.mobadr0.photo_hash # adjust accordingly to your app name and
    
apps:
  photo-hash:
    command: photo_hash
    extensions: [flutter-master] # Where "master" defines which Flutter channel to use for the build
    plugs:
    - network
    slots:
      - dbus-photo-hash
parts:
  photo-hash:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application
    
architectures:
  - build-on: arm64
  - build-on: amd64
  
